### ISSUE TITLE
hideMessage() not used

### ISSUE THREAD

**Issue by nojhamster** [nuxt/opencollective#5]
Hi !
The `OPENCOLLECTIVE_HIDE` variable doesn't have any effect. In production or integration environnements, the message should not appear and no HTTP request should be performed.

If I understand correctly, the [init function](https://github.com/nuxt/opencollective/blob/4673fa06858ffb04e0b9c065497577edbc8f0fd0/src/init.js#L6) should just return when the `hide` variable is set.

**Comment by manniL** [comment]
That's right. That bug must've been introduced during https://github.com/nuxt/opencollective/commit/4673fa06858ffb04e0b9c065497577edbc8f0fd0 :thinking: 	

Would you mind submitting a PR? :relaxed:

**Comment by nojhamster** [comment]
That's done, thanks ! :smile:
